# Generated by Django 5.2 on 2025-05-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='cuerpo',
            field=models.TextField(),
        ),
    ]
